### ISSUE TITLE
Signature verification of push package failed

### ISSUE THREAD

**Issue by siddo420** [MySiteApp/node-safari-push-notifications#6]
I followed all instructions but still getting the following error from Safari.

Signature verification of push package failed

I have already double checked push IDs on client and server and used certificates and keys multiple times.

**Comment by siddo420** [comment]
on the same issue, I might be hitting the problem as you mentioned in your description
```
When building this module, the PKCS7_Sign and SMIME_write_PKCS7 embedded in OS X 10.9 continued to fail. So I copied OpenSSL 0.9.8's version and it works just as the companion example from Apple.
```
How did you do "I copied OpenSSL 0.9.8's version" ? I was under the impression that your module takes care of this under the hood, is it true?

Please explain the steps (for Linux/Mac OSX).

**Comment by kobim** [comment]
Resolved with #5 and ver 0.2.0

**Comment by gbhrdt** [comment]
I am still getting this error when using the intermediate certificate and the exact same code from the README. I also double-checked my certificate and private key.

My cert.pem starts like this:
    -----BEGIN CERTIFICATE-----

My key.pem starts like this:
    -----BEGIN RSA PRIVATE KEY-----

**Comment by yurypaleev** [comment]
Hi, still, there are cases of this error
